---
- hosts: build
  tasks:
    - name: Install required packages
      become: true
      apt:
        name: "{{item}}"
        state: present
      with_items:
        - default-jdk
        - python3-pip
        - docker.io
        - maven
      state: present
      update_cache: true

    - name: Download project
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /tmp

    - name: Run mvn clean in boxfuse folder
      shell:
        cmd: mvn clean package
        chdir: /tmp/boxfuse

    - name: Synchronize project folder on build host with webapps folder on prod host
      synchronize:
        mode: pull
        dirs: no
        src: /tmp/boxfuse/target/hello-1.0.war
        dest: /var/lib/tomcat9/webapps/
      delegate_to: prod

  - name: deploy war on tomcat

    hosts: prod
    become: yes

    tasks:

    - name: Update packages
      apt:
        update_cache: yes

    - name: Install tomcat
      apt:
        name: tomcat9
        state: present

    - name: Copy hello-1.0.war to tomcat webapps folder
      copy: 
          src: hello-1.0.war
          dest: /var/lib/tomcat9/webapps/hello-1.0.war

    - name: Ensure tomcat9 service is started
      service:
        name: tomcat9
        state: started
