- hosts: prod
  tasks:
    - name: Update packages
      apt:
        update_cache: yes

    - name: Install tomcat
      apt:
        name: tomcat9
        state: present

- hosts: build
  tasks:
    - name: Update packages
      apt:
        update_cache: yes

    - name: Install git
      apt:
        name: git
        state: present

    - name: Install maven
      apt:
        name: maven
        state: present

    - name: Download project
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /tmp/boxfuse

    - name: Run mvn clean in boxfuse folder
      shell:
        cmd: mvn clean package
        chdir: /tmp/boxfuse

    - name: Synchronize project folder on build host with webapps folder on prod host
      synchronize:
        mode: pull
        src: /tmp/boxfuse/target/hello-1.0.war
        dest: /var/lib/tomcat9/webapps/
      delegate_to: "{{ groups['prod'][0] }}"

- name: Deploy hello-1.0.war on tomcat

  hosts: prod
  become: yes

  tasks:

    - name: Ensure tomcat is started
      service:
        name: tomcat9
        state: started